spring:
  profiles:
    default: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trusted: com.flightsearch.schemas.jms.PayrollCreate

  mail:
    host: smtp.gmail.com
    port: 587
    username: doc.management24@gmail.com
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
  default-produces-media-type: "application/json"
  default-consumes-media-type: "application/json"
