spring:
  profiles:
    default: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
  default-produces-media-type: "application/json"
  default-consumes-media-type: "application/json"

application:
  openapi:
    dev-url: http://localhost:8080
    helios-url: http://localhost:18080
    prod-url: http://localhost:80