spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    database: postgresql
    generate-ddl: true
  sql:
    init:
      mode: always

application:
  mail:
    log: true
    disable: ${MAIL_DISABLE:false}
    redirect-to: ${MAIL_REDIRECT:""}



