spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    database: postgresql
    generate-ddl: true
  sql:
    init:
      mode: always

  quartz:
    job-store-type: memory
    startup-delay: 5
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.simpl.RAMJobStore
          scheduler:
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

application:
  mail:
    log: true
    disable: ${MAIL_DISABLE:false}
    redirect-to: ${MAIL_REDIRECT:""}



