spring:
  profiles:
    default: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs

application:
  openapi:
    dev-url: http://localhost:8080
    helios-url: http://localhost:18080
    prod-url: http://localhost:80
  repositories:
    base-dir: /Users/klim405/Desktop/ITMO/Code/Java/Web2Lab1-4/src/main/resources
    files-dir: files